source 'https://rubygems.org'
source 'https://rails-assets.org'
ruby '2.0.0'

gem 'rails', '4.1.2'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'slim'
gem 'bootstrap-sass'
gem 'compass-rails'
gem 'autoprefixer-rails'
gem 'sprockets', '2.11.0'
gem 'devise'
gem 'kaminari'
gem 'bootstrap-kaminari-views'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'bcrypt', '~> 3.1.7'
gem 'carrierwave'
gem 'carrierwave-processing'
gem 'mini_magick'
gem 'fog'
gem 'nested_form'
gem 'acts_as_list'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'ancestry'
gem 'chosen-rails'
gem 'jquery-turbolinks'

group :development, :test do
  gem 'sqlite3'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'tapp'
end

group :production do
  gem 'unicorn'
  gem 'pg'
  gem 'asset_sync'
  gem 'unf'
  gem 'therubyracer'
  gem 'rails_12factor'
end
