# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3459da88e825f79e9bfd13b4562804401ff7eb02bafbbd3dc5ebb2334e51f31b4573772b98a1827b0eae7546a13c0fcd43a512609055cab7dc84c17061320ecc

test:
  secret_key_base: 585d5e9f59459816b72af95ee8aa8f0c9a451beb92ebae4a136e3c7072eb3afd34d89ebd05799a98fa2343d482c06e090b0abac8e47c30c4452a191be0ee7721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
